// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: cmd_msg.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandId int32

const (
	CommandId_PING    CommandId = 0
	CommandId_HSET    CommandId = 1
	CommandId_HDEL    CommandId = 2
	CommandId_HGET    CommandId = 3
	CommandId_ZADD    CommandId = 4
	CommandId_ZDELETE CommandId = 5
	CommandId_ZMAX    CommandId = 6
	CommandId_ZMIN    CommandId = 7
)

// Enum value maps for CommandId.
var (
	CommandId_name = map[int32]string{
		0: "PING",
		1: "HSET",
		2: "HDEL",
		3: "HGET",
		4: "ZADD",
		5: "ZDELETE",
		6: "ZMAX",
		7: "ZMIN",
	}
	CommandId_value = map[string]int32{
		"PING":    0,
		"HSET":    1,
		"HDEL":    2,
		"HGET":    3,
		"ZADD":    4,
		"ZDELETE": 5,
		"ZMAX":    6,
		"ZMIN":    7,
	}
)

func (x CommandId) Enum() *CommandId {
	p := new(CommandId)
	*p = x
	return p
}

func (x CommandId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandId) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_msg_proto_enumTypes[0].Descriptor()
}

func (CommandId) Type() protoreflect.EnumType {
	return &file_cmd_msg_proto_enumTypes[0]
}

func (x CommandId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandId.Descriptor instead.
func (CommandId) EnumDescriptor() ([]byte, []int) {
	return file_cmd_msg_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *CommandId `protobuf:"varint,1,opt,name=command,proto3,enum=protocol.CommandId,oneof" json:"command,omitempty"`
	Args    []string   `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_cmd_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommand() CommandId {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return CommandId_PING
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Error  *string  `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cmd_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_cmd_msg_proto protoreflect.FileDescriptor

var file_cmd_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6d, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x5d, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x47, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x5e, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x53, 0x45, 0x54,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x44, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x47, 0x45, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x41, 0x44, 0x44, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x5a, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a,
	0x04, 0x5a, 0x4d, 0x41, 0x58, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x4d, 0x49, 0x4e, 0x10,
	0x07, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x64, 0x6f, 0x6e, 0x73, 0x6b, 0x61, 0x79, 0x61, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cmd_msg_proto_rawDescOnce sync.Once
	file_cmd_msg_proto_rawDescData = file_cmd_msg_proto_rawDesc
)

func file_cmd_msg_proto_rawDescGZIP() []byte {
	file_cmd_msg_proto_rawDescOnce.Do(func() {
		file_cmd_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_msg_proto_rawDescData)
	})
	return file_cmd_msg_proto_rawDescData
}

var file_cmd_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_msg_proto_goTypes = []interface{}{
	(CommandId)(0),   // 0: protocol.CommandId
	(*Command)(nil),  // 1: protocol.Command
	(*Response)(nil), // 2: protocol.Response
}
var file_cmd_msg_proto_depIdxs = []int32{
	0, // 0: protocol.Command.command:type_name -> protocol.CommandId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_msg_proto_init() }
func file_cmd_msg_proto_init() {
	if File_cmd_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_msg_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_cmd_msg_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_msg_proto_goTypes,
		DependencyIndexes: file_cmd_msg_proto_depIdxs,
		EnumInfos:         file_cmd_msg_proto_enumTypes,
		MessageInfos:      file_cmd_msg_proto_msgTypes,
	}.Build()
	File_cmd_msg_proto = out.File
	file_cmd_msg_proto_rawDesc = nil
	file_cmd_msg_proto_goTypes = nil
	file_cmd_msg_proto_depIdxs = nil
}
